name: GruPy-ABC
description: >- # this means to ignore newlines until "baseurl:"
  Grupo para unir os desenvolvedores e usuários de Python da região
  do ABC e do estado de São Paulo.
baseurl: "" # the subpath of your site, e.g. /blog
url: "grupy" # the base hostname & protocol for your site, e.g. http://example.com

author: Desenvolvido por Pavel Makhov.
copyright: 2015-2017

social:
    github: grupy-abc
# Build settings

kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true

theme: minima
plugins:
  - jekyll-feed
